service: bulls-and-cows

plugins:
  - serverless-deployment-bucket
  - serverless-localstack

provider:
  deploymentBucket:
    name: bulls-and-cows-deployment
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"

custom:
  localstack:
    stages:
      - local
    host: http://localhost
    edgePort: 4566
    lambda:
      mountCode: true

functions:
  webhook:
    handler: ./src/webhook.handler
    events:
      - http:
          path: /webhook
          method: get
          cors: true